export const AVEYRON_SERVICE_SECTORS = [
  {
    name: 'Rodez, Vallon de Marcillac et Ségala',
    communes: [
      'Rodez',
      'Onet-le-Château',
      'Sébazac-Concourès',
      'Marcillac-Vallon',
      'Salles-la-Source',
      'Belcastel',
      'Naucelle',
      'Baraqueville',
      'Rignac',
    ],
  },
  {
    name: 'Conques, Decazeville et vallée du Lot',
    communes: [
      'Conques-en-Rouergue',
      'Decazeville',
      'Aubin',
      'Cransac',
      'Firmi',
      'Flagnac',
      'Livinhac-le-Haut',
      'Entraygues-sur-Truyère',
    ],
  },
  {
    name: 'Aubrac, Laguiole et Espalion',
    communes: [
      'Laguiole',
      'Saint-Chély-d’Aubrac',
      'Argences-en-Aubrac',
      'Espalion',
      'Estaing',
      'Saint-Côme-d’Olt',
      'Saint-Geniez-d’Olt-et-d’Aubrac',
      'Bozouls',
    ],
  },
  {
    name: 'Millau, Grands Causses et gorges du Tarn',
    communes: [
      'Millau',
      'Creissels',
      'Rivière-sur-Tarn',
      'Mostuéjouls',
      'Peyreleau',
      'La Cresse',
      'Saint-Beauzély',
      'Nant',
    ],
  },
  {
    name: 'Saint-Affrique, Roquefort et Sud-Aveyron',
    communes: [
      'Saint-Affrique',
      'Roquefort-sur-Soulzon',
      'Vabres-l’Abbaye',
      'Saint-Rome-de-Cernon',
      'Sainte-Eulalie-de-Cernon',
      'La Cavalerie',
      'La Couvertoirade',
      'Camarès',
      'Belmont-sur-Rance',
    ],
  },
  {
    name: 'Villefranche, Najac et Bastides du Rouergue',
    communes: [
      'Villefranche-de-Rouergue',
      'Najac',
      'Villeneuve',
      'Sauveterre-de-Rouergue',
      'Rieupeyroux',
      'La Fouillade',
      'Monteils',
    ],
  },
];
