import type { LocalSource, LocalTableRow } from '../types';

export const GIRONDE_TOURISM_ROWS: LocalTableRow[] = [
  { key: 'lits-touristiques', label: 'Lits touristiques en Gironde en 2024', value: '561 000' },
  { key: 'lits-marchands', label: 'Lits marchands', value: '261 000' },
  {
    key: 'part-meubles-locations',
    label: 'Part des meublés et locations dans les lits marchands',
    value: '38 %',
  },
  {
    key: 'logements-plateformes',
    label: 'Logements entiers proposés sur Airbnb, Booking et Abritel en 2024',
    value: '46 000',
  },
  { key: 'nuitees-touristiques', label: 'Nuitées touristiques en 2025', value: '47,4 M' },
];

export const GIRONDE_SERVICE_SECTORS = [
  {
    name: 'Bordeaux Métropole et rive droite',
    communes: [
      'Bordeaux',
      'Mérignac',
      'Pessac',
      'Talence',
      'Bègles',
      'Cenon',
      'Lormont',
      'Floirac',
      'Le Bouscat',
      'Bruges',
      'Eysines',
      'Blanquefort',
      'Ambarès-et-Lagrave',
      'Bouliac',
      'Artigues-près-Bordeaux',
    ],
  },
  {
    name: 'Coteaux bordelais et Saint-Loubès',
    communes: [
      'Tresses',
      'Fargues-Saint-Hilaire',
      'Carignan-de-Bordeaux',
      'Sallebœuf',
      'Yvrac',
      'Sainte-Eulalie',
      'Saint-Loubès',
      'Saint-Sulpice-et-Cameyrac',
      'Beychac-et-Caillau',
      'Montussan',
      'Latresne',
      'Camblanes-et-Meynac',
      'Quinsac',
      'Langoiran',
    ],
  },
  {
    name: 'Montesquieu et sud de Bordeaux',
    communes: [
      'La Brède',
      'Léognan',
      'Martillac',
      'Cadaujac',
      'Beautiran',
      'Saint-Médard-d’Eyrans',
      'Saucats',
      'Ayguemorte-les-Graves',
      'Castres-Gironde',
      'Saint-Selve',
    ],
  },
  {
    name: 'Libournais, Fronsadais et Saint-Émilion',
    communes: [
      'Libourne',
      'Saint-Émilion',
      'Pomerol',
      'Fronsac',
      'La Lande-de-Fronsac',
      'Galgon',
      'Vérac',
      'Coutras',
      'Saint-Denis-de-Pile',
      'Izon',
      'Vayres',
      'Guîtres',
      'Saint-Seurin-sur-l’Isle',
      'Lussac',
      'Puisseguin',
      'Montagne',
      'Saint-Sulpice-de-Faleyrens',
    ],
  },
  {
    name: 'Castillon, Pays Foyen et est girondin',
    communes: [
      'Castillon-la-Bataille',
      'Saint-Magne-de-Castillon',
      'Branne',
      'Rauzan',
      'Gensac',
      'Pujols',
      'Sainte-Foy-la-Grande',
      'Pineuilh',
      'Pellegrue',
      'Saint-Avit-Saint-Nazaire',
      'Eynesse',
    ],
  },
  {
    name: 'Haute-Gironde, Blayais et Cubzaguais',
    communes: [
      'Saint-André-de-Cubzac',
      'Cubzac-les-Ponts',
      'Bourg',
      'Blaye',
      'Saint-Ciers-sur-Gironde',
      'Étauliers',
      'Eyrans',
      'Val-de-Livenne',
      'Braud-et-Saint-Louis',
      'Cavignac',
      'Saint-Savin',
      'Saint-Yzan-de-Soudiac',
      'Laruscade',
    ],
  },
  {
    name: 'Entre-deux-Mers et vallée de la Garonne',
    communes: [
      'Créon',
      'Sadirac',
      'La Sauve',
      'Targon',
      'Sauveterre-de-Guyenne',
      'Monségur',
      'La Réole',
      'Gironde-sur-Dropt',
      'Cadillac-sur-Garonne',
      'Podensac',
      'Cérons',
      'Barsac',
      'Preignac',
      'Langon',
      'Toulenne',
      'Fargues',
      'Roaillan',
      'Bazas',
    ],
  },
];

export const GIRONDE_SOURCES: LocalSource[] = [
  {
    label: 'Gironde Tourisme — Chiffres clés 2025',
    href: 'https://www.gironde-tourisme.com/espace-pro/wp-content/uploads/sites/2/2025/06/Chiffres-cles-2025.pdf',
  },
  {
    label: 'Gironde Tourisme — Enquête clientèle 2025',
    href: 'https://www.gironde-tourisme.com/espace-pro/2026/05/29/enquete-clientele-tourisme-gironde-2025/',
  },
  {
    label:
      'INSEE — En Nouvelle-Aquitaine, les locations de meublés touristiques en forte progression',
    href: 'https://www.insee.fr/fr/statistiques/8673310',
  },
  {
    label: 'Atout France — Classement des meublés de tourisme',
    href: 'https://www.atout-france.fr/fr/classement/meuble-de-tourisme',
  },
  {
    label: 'Direction générale des Entreprises — Les meublés de tourisme',
    href: 'https://www.entreprises.gouv.fr/espace-entreprises/s-informer-sur-la-reglementation/les-meubles-de-tourisme',
  },
  {
    label: 'Service-Public — Déclaration en mairie des meublés de tourisme',
    href: 'https://www.service-public.fr/particuliers/vosdroits/R14321',
  },
  {
    label: 'Service-Public Entreprendre — Taxe de séjour touristique',
    href: 'https://entreprendre.service-public.gouv.fr/vosdroits/F31635',
  },
  {
    label: 'Bordeaux — Location touristique à Bordeaux, guide propriétaires',
    href: 'https://www.bordeaux.fr/location-touristique-bordeaux--guide-proprietaires',
  },
  {
    label: 'Bordeaux Métropole — Taxe de séjour',
    href: 'https://taxedesejour.bordeaux-metropole.fr/',
  },
  {
    label: 'Grand Saint-Émilionnais — Taxe de séjour',
    href: 'https://grandsaintemilionnais.taxesejour.fr/',
  },
];
