export const LOT_SERVICE_SECTORS = [
  {
    name: 'Cahors et la Vallée du Lot',
    communes: [
      'Cahors',
      'Pradines',
      'Mercuès',
      'Douelle',
      'Luzech',
      'Prayssac',
      'Puy-l’Évêque',
      'Albas',
    ],
  },
  {
    name: 'Rocamadour et la Vallée de la Dordogne',
    communes: [
      'Rocamadour',
      'Gramat',
      'Padirac',
      'Martel',
      'Souillac',
      'Carennac',
      'Autoire',
      'Loubressac',
      'Saint-Céré',
      'Bretenoux',
    ],
  },
  {
    name: 'Figeac et la Vallée du Célé',
    communes: [
      'Figeac',
      'Capdenac',
      'Cajarc',
      'Cardaillac',
      'Marcilhac-sur-Célé',
      'Espagnac-Sainte-Eulalie',
      'Lacapelle-Marival',
      'Bagnac-sur-Célé',
    ],
  },
  {
    name: 'Saint-Cirq-Lapopie et les Causses du Quercy',
    communes: [
      'Saint-Cirq-Lapopie',
      'Tour-de-Faure',
      'Bouziès',
      'Cabrerets',
      'Limogne-en-Quercy',
      'Lalbenque',
      'Cœur de Causse',
      'Assier',
    ],
  },
  {
    name: 'Gourdon, la Bouriane et le Quercy Blanc',
    communes: [
      'Gourdon',
      'Le Vigan',
      'Payrac',
      'Catus',
      'Salviac',
      'Cazals',
      'Montcuq-en-Quercy-Blanc',
      'Castelnau-Montratier',
    ],
  },
];
